{
    "model_type": "skip-mini",
    "input_shape": 4,
    "amplitude_shape": 36,
    "data_dir": "/scratch/hakula/dataset",
    "seed": 42,
    "var_y": 'all',
    "use_MC_sample": False,
    "train-sample-size": 10_000_000,
    "validate-sample-size": 500_000,
    "test-sample-size": 500_000,
    "activation": "leaky_relu",
    "width": 160,
    "depth": 16,
    "skip_block_layers": 6,
    # "beta": 0,
    # "alpha": 0,
    # "normal_scaled": False,
    "lr_decay_type": "plateau",
    "initial_lr": 0.001,
    # "final_lr": 1e-6,
    "lr_patience": 25,
    "lr_factor": 0.8,
    "lr_delta": 7e-5,
    # "decay_steps": 200,
    "batch_size": 2048,
    "steps_per_epoch": 2400,
    "early_stopping_start_epoch": 100,
    "patience": 40,
    # "monitor": "val_mse",
    "loss": "huber",
    "gradient_clipping": True,
    # "verbose": 1,
    "base_directory": "../models/",
    "epochs": 2000,
    "model-uuid": "UUID"
}